### ISSUE TITLE
Doesn't build on windows

### ISSUE THREAD

**Issue by insominx** [zhm/node-spatialite#7]

**Comment by insominx** [comment]
Sorry for the lack of detail...  It looks like it's related to the definition of min and max.  It shows up several times but here's one them:

..\..\..\..\..\src\spatialite\deps\geos\geos\src\geom\LineSegment.cpp(171): error C3861: 'max': identifier not found [D:\Projects\Android\SSEDock\node_modules\spatialite\build\src\spatialite\deps\geos\geos.vcxproj]
..\..\..\..\..\src\spatialite\deps\geos\geos\src\geom\LineSegment.cpp(174): error C3861: 'max': identifier not found [D:\Projects\Android\SSEDock\node_modules\spatialite\build\src\spatialite\deps\geos\geos.vcxproj]

Someone actually has a branch that looks like it addresses these here: https://github.com/cartant/node-spatialite/commit/da190997294ab400a0817278b80c3e067639a087 

but that one also does not build for different reasons related to gyp:

gyp: src\spatialite\deps\lwgeom\binding.gyp not found (cwd: ...\node_modules\spatialite) while loading dependencies of binding.gyp while trying to load binding.gyp

**Comment by david-wilson** [comment]
I am experiencing this same issue. I am using Windows 8.1, with VS 12 installed. My errors look like this:

..\..\..\..\..\src\spatialite\deps\geos\geos\src\algorithm\LineIntersector.cpp(
80): error C3861: 'max': identifier not found [<redacted>\node_modules\spatialite\build\src\spatialite\deps\geos\geos.vcxproj]

**Comment by TesseractG** [comment]
I managed to fix the build issues on Windows. You can find my fork here;

https://github.com/TesseractG/node-spatialite.git

Note that you also have to run git submodule update -i -r on the checked out repository, or you will be missing lwgeom, as mentioned in the last error by insominx.

node-gyp rebuild works on this repos (for me), but I still cannot get the package to run. If I build it locally, run npm install on it for the dependencies and drop it into my global node_modules, npm list shows it as "invalid" without any further information.

If I try to install it using npm install https://github.com/TesseractG/node-spatialite.git, it does NOT auto-download the lwgeom package and dies on that.

I am still trying to figure it out, but at least it is building...

**Comment by zhm** [comment]
What version of Windows + VS are you using? I would be interested to accept a PR that fixes Windows, but I don't use Windows and haven't had time to debug it. It's been long enough now that it's also probably time to upgrade all the dependencies.

**Comment by TesseractG** [comment]
I am on Windows 10 using Visual Studio 2015 - so latest versions of both.

The problem with issuing a PR is that I cannot guarantee these changes do not break builds on any other platforms...

**Comment by TesseractG** [comment]
I have all of it working now on Windows with VS 2015. I had to make some changes to lwgeom as well and I am pretty sure those changes will break compatibility with earlier versions of VS, since they concern fixing mistakes previously present in VS (like not defining NAN and INFINITE).

I can issue merge requests for both. lwgeom will continue to build on all *nix environments and will only build on Windows with VS2015. node-spatialite may or may not build on other environments; I do not know.

Please let me know how you would like to proceed.

**Comment by zhm** [comment]
I would say please submit a PR! I can test it on Mac and Linux. As far as I know, Windows doesn't work at all at the moment, so I don't think it could work any less ;)

**Comment by zhm** [comment]
Also, do you need lwgeom? I'm considering removing it to simplify the build process because it makes things significantly more complicated to build...

**Comment by TesseractG** [comment]
I am not sure if I need lwgeom, all I know is that the package does not compile/install without it. I am using it in a software package that was developed by someone else (who runs it on a Mac without any issues), so I am not sure if it is needed...

I will issue the merge requests on both projects now.

**Comment by zachatrocity** [comment]
@TesseractG with your latest fork/PR does `npm install https://github.com/TesseractG/node-spatialite.git` auto download lwgeom for you? Or are you cloning, running `git submodule update -i -r` and then building to get it to work on windows?

**Comment by zachatrocity** [comment]
I'm very close but Its not quite finishing the build. Here is the error

```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\..\..\src\spatia
lite\deps\lwgeom\lwgeom\lwgeom_geos_split.c) [C:\Users\zrussell1\Documents\Pinpoint\libs\node-spatialite\build\src\spat
ialite\deps\lwgeom\lwgeom.vcxproj]
```

I have this same error across most of the files in lwgeom

**Comment by TesseractG** [comment]
I get lwgeom using git submodule update - I am not sure if there is a way to do this automatically. Your NPM package (the one that downloads using npm install) has lwgeom in there, though. I assume you need to special build a release package including all external libraries?

As for the snprintf errors; those are the errors I fixed... If you ook at the changes I made to the config files for win32 and win64 in the commit, then you can see that I removed the superfluous define of snprintf. This error occurred for me too at first, but no longer...

I just did a search for snprintf on all source files I have of lwgeom and the macro no longer appears anywhere. Are you sure you are using my version?

**Comment by zachatrocity** [comment]
Here is the exact process I'm going through:

```
git clone https://github.com/TesseractG/node-spatialite.git
...
cd node-spatialite
git submodule update -i -r
...
node-gyp configure build
```
I thought I found the [issue](https://github.com/TesseractG/node-spatialite/blob/master/.gitmodules#L3). So I replaced the submodule to download your lwgeom fork however still the same snprintf errors.

**Comment by zhm** [comment]
I published `0.0.6`, could you try that?

```
npm install spatialite@0.0.6
```

**Comment by zachatrocity** [comment]
That worked great for me. Built with no issues on Windows 7 with VS 2015

**Comment by TesseractG** [comment]
Worked fine for me too! Windows 10 with VS 2015.

Whatever the issue with the lwgeom module was, it does not seem to affect me... I think this is good for building on Windows. Thanks for merging!

**Comment by zhm** [comment]
Great! Thanks for the PR @TesseractG and for testing it out!
